const SEARCH_TYPES = {
  BREADTH_FIRST : "BREADTH_FIRST",
  DEPTH_FIRST_PRE_ORDER: "PRE_ORDER",
  DEPTH_FIRST_IN_ORDER: "IN_ORDER",
  DEPTH_FIRST_POST_ORDER: "POST_ORDER",
}

module.exports = { SEARCH_TYPES };
